name: llama-3-70b-gpu-large-server
message: Quickstart to serve Llama 3 chatbot
image: quay.io/vessl-ai/torch:2.3.1-cuda12.1-r5
resources:
  cluster: vessl-gcp-oregon
  preset: gpu-l4-large
run:
- command: |
    pip install ray
    pip install autoawq==0.2.4
    pip install vllm==v0.4.1 fastapi==0.109.2
    pip uninstall -y transformer-engine
    pip install flash-attn==2.5.7
    python -m vllm.entrypoints.openai.api_server --model $MODEL_NAME --tensor-parallel-size $TENSOR_PARALLEL_SIZE --gpu-memory-utilization $GPU_MEMORY_UTILIZATION --enforce-eager
  workdir: /root
env:
  MODEL_NAME: casperhansen/llama-3-70b-instruct-awq
  TENSOR_PARALLEL_SIZE: 4
  GPU_MEMORY_UTILIZATION: 0.9
ports:
- port: 8000
service:
  autoscaling:
    max: 1
    metric: cpu
    min: 1
    target: 50
  expose: 8000

