name: gemma2-kor-ui
message: gemma2-kor-ui
image: quay.io/vessl-ai/torch:2.3.1-cuda12.1-r5
resources:
  cluster: vessl-aws-seoul
  preset: cpu-medium
import:
  /app/: git://github.com/vessl-ai/examples.git
run:
  - command: |
      pip install -r requirements.txt
      python app.py
    workdir: /app/gemma2-kor-ui
env:
  OPENAI_API_KEY: helloworld
ports:
  - port: 7860
service:
  autoscaling:
    max: 2
    metric: cpu
    min: 1
    target: 50
  expose: 7860
